#!/bin/bash


cd src/turbulenceModels/incompressible/LES/
rmdepall
wclean
cd ../../../../

cd src/turbineModels
rmdepall
wclean
cd ../../

cd src/finiteVolume
rmdepall
wclean
cd ../../

cd applications/utilities/setFieldsABL
rmdepall
wclean
cd ../../../

cd applications/utilities/rotateFields
rmdepall
wclean
cd ../../../

cd applications/solvers/incompressible/windEnergy/ABLSolver
rmdepall
wclean
cd ../../../../../

cd applications/solvers/incompressible/windEnergy/ABLTerrainSolver
rmdepall
wclean
cd ../../../../../

cd applications/solvers/incompressible/windEnergy/windPlantSolver
rmdepall
wclean
cd ../../../../../

cd applications/solvers/incompressible/windEnergy/windPlantSolver.ADM
rmdepall
wclean
cd ../../../../../

cd applications/solvers/incompressible/windEnergy/windPlantSolver.ALMAdvanced
rmdepall
wclean
cd ../../../../../

cd applications/solvers/incompressible/windEnergy/pisoFoamTurbine
rmdepall
wclean
cd ../../../../../

cd applications/solvers/incompressible/windEnergy/pisoFoamTurbine.ADM
rmdepall
wclean
cd ../../../../../

cd applications/solvers/incompressible/windEnergy/pisoFoamTurbine.ALMAdvanced
rmdepall
wclean
cd ../../../../../

cd applications/solvers/incompressible/windEnergy/turbineTestHarness
rmdepall
wclean
cd ../../../../../

cd applications/solvers/incompressible/windEnergy/turbineTestHarness.ALMAdvanced
rmdepall
wclean
cd ../../../../../
