#!/bin/bash


cd src/turbulenceModels/incompressible/LES/
wmake libso
cd ../../../../

cd src/turbineModels
wmake libso
cd ../../

cd src/finiteVolume
wmake libso
cd ../../

cd applications/utilities/setFieldsABL
wmake
cd ../../../

cd applications/utilities/setFieldsABL2
wmake
cd ../../../

cd applications/utilities/rotateFields
wmake
cd ../../../

cd applications/solvers/incompressible/windEnergy/ABLSolver
wmake
cd ../../../../../

cd applications/solvers/incompressible/windEnergy/ABLTerrainSolver
wmake
cd ../../../../../

cd applications/solvers/incompressible/windEnergy/windPlantSolver
wmake
cd ../../../../../

cd applications/solvers/incompressible/windEnergy/pisoFoamTurbine
wmake
cd ../../../../../

cd applications/solvers/incompressible/windEnergy/turbineTestHarness
wmake
cd ../../../../../
